### ISSUE TITLE
Fetch/Get icons from the `develop` branch

### ISSUE THREAD

**Issue by Panquesito7** [maltejur/react-devicons#1]
Maybe you should fetch/get the icons from the `develop` branch. All-new icons are added in that branch. The `develop` branch gets merged in the `master` branch in a new release. What do you think?

Thanks. 🙂

**Comment by maltejur** [comment]
I don't think that would work, because how the repo works is it will create a new release here when a new release is published on devicon. So it mirrors the devicon version.

**Comment by Panquesito7** [comment]
So, what is the purpose of using `react-devicons` if it's a mirror of Devicons? 🤔

**Comment by maltejur** [comment]
It provides react components for the SVG icons from devicons. It only mirrors the version number, if that wasn't clear.

**Comment by Panquesito7** [comment]
Ahh, I see. Thanks for explaining! 🙂
