### ISSUE TITLE
Repo still has references to the old repo

### ISSUE THREAD

**Issue by Thomas-Boi** [maltejur/react-devicons#2]
In the `publish.ts` file, I noticed that a few lines of code still reference the old repo from @maltejur.
![image](https://user-images.githubusercontent.com/43018778/132582874-345bb98e-80cc-466e-95c9-c18b5106fea1.png)

I think it might be a good idea to update them to the current repo instead.

**Comment by maltejur** [comment]
Oh yes, good catch. For now, GitHub will redirect those requests. But I was planning to rewrite the whole publish process nevertheless because now that the repo is in the org I can just trigger the workflow directly.
