### ISSUE TITLE
Daily workflow "npm publish"

### ISSUE THREAD

**Issue by amacado** [maltejur/react-devicons#3]
Is there a reason why the workflow https://github.com/devicons/react-devicons/blob/main/.github/workflows/publish.yaml is running on a daily base publishing the package over and over again?

**Comment by maltejur** [comment]
Right now it runs every day and checks if there is a new version. I had to to it like this because there was no way to trigger a publish when another repo creates a release. But I will rework the whole file to only run when the main repo creates a release in a few days.
